# Generated by Django 4.2.16 on 2024-11-03 13:25

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.PositiveIntegerField(verbose_name="Часы")),
            ],
            options={
                "verbose_name": "Интервал между постами",
                "verbose_name_plural": "Интервал между постами",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", markdownx.models.MarkdownxField(verbose_name="Текст")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
