version: '3.8'

services:
  web:
    build: .
    container_name: sto_sunn_web
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --chdir /app/sto_sunn/ sto_sunn.wsgi:application"
    volumes:
      - .:/app
      - media_volume:/app/sto_sunn/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
  nginx:
    image: nginx:1.21-alpine
    container_name: sto_sunn_nginx
    volumes:
      - media_volume:/app/sto_sunn/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
  db:
    image: postgres:17.0-alpine
    container_name: sto_sunn_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
volumes:
  pgdata:
  media_volume:
  conf:
