version: '3.8'

services:
  web:
    build: .
    container_name: sto_sunn_web
    command: sh -c "gunicorn --bind 0.0.0.0:8000 --chdir /app/sto_sunn/ sto_sunn.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
  db:
    image: postgres:17.0-alpine
    container_name: sto_sunn_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
volumes:
  pgdata:
