default_language_version:
  python: python3.10
repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --remove-all-unused-imports --ignore-init-module-imports -ir .
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: system
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        additional_dependencies: [ 'click==8.0.4' ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [ types-requests, types-redis, types-pytz, types-filelock, types-python-dateutil, types-cryptography ]
        args: [--implicit-optional, --ignore-missing-imports, --disable-error-code, "annotation-unchecked"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-fixme,
          flake8-print,
        ]

